### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by jayvdb** [Roskus/OpenSQLManager#2]
It looks like this only supports sqlite and mysql.  I havent checked these.  If they are working it would be useful to explain how to set these up in the config , and also note in the README which dbs are supported.

**Comment by gnovaro** [comment]
Yes, this app was first test for made something more complex. But i thinking i not really a good choose use Tkinter for rich UI, for a simple app maybe is enough. I you want to try can simple edit the config.yml in the src folder. I test with mariadb and works fine. 
I strongly recommend to see this project https://github.com/beekeeper-studio/beekeeper-studio
